/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interprac4;

import Acesso.DAO.Conexion;
import Acesso.DTO.DatosDTO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mk
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    List<DatosDTO> ListaDatos = new ArrayList();
    DatosDTO datosDTO;
    
    DefaultTableModel tablamodelo = new DefaultTableModel();
    public PrincipalJFrame() {
        initComponents();
        cargartitulos();
        Conexion conexion = new Conexion();
        conexion.abrirconexion();
        if(conexion.LeerDatos()){
            ListaDatos = conexion.Listado(); 
            cargarcontenido();
        }
        conexion.cerrarconexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        btnregistra = new javax.swing.JButton();
        btnlista = new javax.swing.JButton();
        btnactualiza = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Agenda en java y MariaDB");

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        btnregistra.setText("Registra");
        btnregistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistraActionPerformed(evt);
            }
        });

        btnlista.setText("Actualizar Lista");
        btnlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistaActionPerformed(evt);
            }
        });

        btnactualiza.setText("Actulizar Datos");
        btnactualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizaActionPerformed(evt);
            }
        });

        btnborrar.setText("Borrar Datos");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnactualiza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(304, 304, 304))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnregistra)
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnborrar)
                            .addComponent(btnlista))
                        .addGap(152, 152, 152))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistra)
                    .addComponent(btnlista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualiza)
                    .addComponent(btnborrar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistraActionPerformed
        // TODO add your handling code here:
        CapturaJFrame capturaJFrame = new CapturaJFrame();
        capturaJFrame.setVisible(true);
        
        capturaJFrame.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e){
                JOptionPane.showMessageDialog(PrincipalJFrame.this, "aqui");
            }
        });
    }//GEN-LAST:event_btnregistraActionPerformed

    private void btnlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistaActionPerformed
        // TODO add your handling code here:
        TablaDatos.removeAll();
        tablamodelo = new DefaultTableModel();
        Conexion conexion = new Conexion();
        conexion.abrirconexion();
        if (conexion.LeerDatos()){
            ListaDatos.clear();
            ListaDatos = conexion.Listado();
            cargartitulos();
            cargarcontenido();
        }
        
    }//GEN-LAST:event_btnlistaActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        // TODO add your handling code here:
        int nfilas=0;
        int fila=0;
        int vid=0,edad=0;
        String nombre="",correo="";
        
        
        nfilas = TablaDatos.getSelectedRowCount();
        if (nfilas == 1){
            fila = TablaDatos.getSelectedRow();
            vid =(int) TablaDatos.getValueAt(fila, 0);
            nombre = (String) TablaDatos.getValueAt(fila,1);
            edad = (int) TablaDatos.getValueAt(fila,2);
            correo = (String) TablaDatos.getValueAt(fila,3);
            datosDTO = new DatosDTO(vid,nombre,edad,correo);
        }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void btnactualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizaActionPerformed
        // TODO add your handling code here:
        ActualizaJFrame actualizaJFrame = new ActualizaJFrame(datosDTO);
        actualizaJFrame.setVisible(true);
        actualizaJFrame.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e) {
            TablaDatos.removeAll();
                tablamodelo = new DefaultTableModel();
                Conexion conexion = new Conexion();
                conexion.abrirconexion();
                if (conexion.LeerDatos()){
                    ListaDatos.clear();
                    ListaDatos = conexion.Listado();
                    cargartitulos();
                    cargarcontenido();
                }
            }
        
    });
    }//GEN-LAST:event_btnactualizaActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // TODO add your handling code here:
        Conexion conexion = new Conexion();
        
        int res = JOptionPane.showConfirmDialog(this, "estas seguro de borrar el registro?");
        if (res == JOptionPane.OK_OPTION){
            conexion.abrirconexion();
            if (conexion.BorrarDatos(datosDTO.getId())){
                JOptionPane.showMessageDialog(this, "Se elimino correctamente");
                TablaDatos.removeAll();
                tablamodelo = new DefaultTableModel();
                ListaDatos.clear();
                ListaDatos = conexion.Listado();
                cargartitulos();
                cargarcontenido();
            }
        }
       
        
    }//GEN-LAST:event_btnborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }
    
    private void cargartitulos(){
        tablamodelo.addColumn("ID");
        tablamodelo.addColumn("Nombre");
        tablamodelo.addColumn("Edad");
        tablamodelo.addColumn("Correo");
        TablaDatos.setModel(tablamodelo);
    }
    
    private void cargarcontenido (){
        Object[] filas = new Object[4];
        for (DatosDTO datos : ListaDatos){
            filas[0] = datos.getId();
            filas[1] = datos.getNombre();
            filas[2] = datos.getEdad();
            filas[3] = datos.getCorreo();
            tablamodelo.addRow(filas);
        }
        TablaDatos.setModel(tablamodelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnactualiza;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnlista;
    private javax.swing.JButton btnregistra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
